version: "2"

checks:
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 400
  method-lines:
    config:
      threshold: 40
  method-count:
    config:
      threshold: 40
  return-statements:
    config:
      threshold: 5
  method-complexity:
    config:
      threshold: 10

exclude_patterns:
  - "**/.idea/*"
  - "examples/*"
  - "jest.config.js"
  - "pnpmfile.js"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          # make it higher so it does not report bullshit like similarity of abstract method and its implementation
          mass_threshold: 75
