packages:
  - 'tools/*'
  - 'website'
  - 'packages/*'
  - 'examples/*'
  - '.'
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: true
  core-js-pure: true
  unrs-resolver: true
  zstd-napi: true
