on: [push]
jobs:
  building:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - NODE_VERSION=10
          - NODE_VERSION=12
          - NODE_VERSION=14
          - NODE_VERSION=16

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Start services hosted by docker-compose
        run: |-
          docker-compose up -d zookeeper kafka-1 kafka-2 kafka-3

      - name: Build
        run: |-
          echo "Building docker image for workspace with NODE_VERSION=${NODE_VERSION}"
          docker-compose build workspace-test

      - name: Test
        run: |-
          docker-compose run workspace-test

      - name: Upload Coverage info
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: coverage/lcov.info:lcov
          debug: true

