on: [push]
jobs:
  building:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14
          - 16
          - 18

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - run: |-
          docker-compose pull
          docker-compose up -d kafka-1 kafka-2 kafka-3

      - name: BuildAndPush
        uses: docker/build-push-action@v4
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: NODE_VERSION=${{ matrix.node-version }}
          tags: workspace-test

      - name: Test
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |-
          docker-compose run workspace-test

      - name: Upload Coverage info to CodeClimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: coverage/lcov.info:lcov
          debug: true
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/lcov.info
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>

