on: [push]

env:
  IMAGE_TAG: sensejs/workspace:test

jobs:
  building:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 21

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up E2E Test Environment
        run: |-
          docker-compose pull kafka-1 kafka-2 kafka-3 minio
          docker-compose up -d kafka-1 kafka-2 kafka-3 minio

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha,scope=node-v${{ matrix.node-version }}
          cache-to: type=gha,mode=max,scope=node-v${{ matrix.node-version }}
          build-args: NODE_VERSION=${{ matrix.node-version }}
          load: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Test
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |-
          docker-compose run test-workspace

      - name: Upload Coverage info to CodeClimate
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: coverage/lcov.info:lcov
          debug: true

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/lcov.info
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>

