on: [push]
jobs:
  building:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16
          - 18

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - run: |-
          docker-compose pull
          docker-compose up -d kafka-1 kafka-2 kafka-3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |-
          echo "Building docker image for workspace with NODE_VERSION=${NODE_VERSION}"
          docker-compose build --build-arg=NODE_VERSION=$NODE_VERSION workspace-test

      - name: Test
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |-
          docker-compose run workspace-test

      - name: Upload Coverage info
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: coverage/lcov.info:lcov
          debug: true

